services:
  django:
    build:
      context: ./django
    volumes:
      - ./django:/usr/src/app
    # command: python manage.py runserver
    command: gunicorn transcande.wsgi:application --bind
    expose:
      - 8000
    env_file:
      - ./.env/dev.env
  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
